### ISSUE TITLE
Create more user-friendly error message for when NOMP doesn't have permission to use port 80 for website

### ISSUE THREAD

**Issue by mapleshadow** [zone117x/node-open-mining-portal#141]
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: bind EACCES
    at errnoException (net.js:904:11)
    at net.js:1072:30
    at Object.12:1 (cluster.js:592:5)
    at handleResponse (cluster.js:171:41)
    at respond (cluster.js:192:5)
    at handleMessage (cluster.js:202:5)
    at process.EventEmitter.emit (events.js:117:20)
    at handleMessage (child_process.js:322:10)
    at Pipe.channel.onread (child_process.js:349:11)
2014-05-05 17:21:19 [Master]    [Website] Website process died, spawning replacement...
## xxxxx@mpos:~/nomp$ 

PS:
config.json

```
"website": {
    "enabled": true,
    "port": 80,
    "stratumHost": "localhost",
    "stats": {
        "updateInterval": 60,
        "historicalRetention": 43200,
        "hashrateWindow": 300
    },
    "adminCenter": {
        "enabled": true,
        "password": "password"
    }
},
```

**Comment by bitcoinbrisbane** [comment]
I had the same issue.  I solved by changing port to 8080 and the ip address in the config file to 127.0.0.1 and then ran as sudo.

**Comment by sysmanalex** [comment]
+ nginx proxy
proxy_cache_path /var/lib/nginx/proxy levels=1:2 keys_zone=api:5m;

        location ~ ^/(tbs|workers|stats|blocks) {
          proxy_pass    http://127.0.0.1:8080;
        }

        location ~ ^/static {
          proxy_pass    http://127.0.0.1:8080;
          expires 15m;
        }

        location ~ ^/api/(live|pool)_stats {
          proxy_pass    http://127.0.0.1:8080;
          proxy_cache api;
          proxy_cache_key $scheme$proxy_host$uri;
          proxy_cache_lock on;
          proxy_cache_valid 3m;
          proxy_cache_lock_timeout 30s;

          expires 3m;

        }
