### ISSUE TITLE
Could not start pool, error with init batch RPC call "socket hang up"

### ISSUE THREAD

**Issue by fangx4** [zone117x/node-open-mining-portal#207]
[Pool]      [darkcoin](Thread 16) Could not start pool, error with init batch RPC call: {"type":"request error","message":"socket hang up"}

---

 darkcoind getinfo
{
    "version" : 90303,
    "protocolversion" : 70014,
    "walletversion" : 60000,
    "balance" : 0.00000000,
    "blocks" : 68884,
    "timeoffset" : 3,
    "connections" : 8,
    "proxy" : "",
    "difficulty" : 2152.32913398,
    "testnet" : false,
    "keypoololdest" : 1400056158,
    "keypoolsize" : 101,
    "paytxfee" : 0.00000000,
    "mininput" : 0.00001000,
    "errors" : ""
## }

darkcoin.json:

{
    "enabled": true,
    "coin": "darkcoin.json",

```
"address": "********",

"rewardRecipients": {
    "XcQmhp8ANR7okWAuArcNFZ2bHSB81jpapQ": 1.5,
},

"paymentProcessing": {
    "enabled": false,
    "paymentInterval": 20,
    "minimumPayment": 70,
    "daemon": {
        "host": "localhost",
        "port": 22556,
        "user": "******",
        "password": "*********"
    }
},

"ports": {
    "6610": {
        "diff": 16
    },
    "6616": {
        "diff": 64,
        "varDiff": {
            "minDiff": 64,
            "maxDiff": 1024,
            "targetTime": 12,
            "retargetTime": 90,
            "variancePercent": 30
        }
    },
    "6617": {
        "diff": 128
    },
    "6618": {
        "diff": 256
    }
},

"daemons": [
    {
        "host": "localhost",
        "port": 22556,
        "user": "********",
        "password": "**********"
    }
],

"p2p": {
    "enabled": false,
    "host": "127.0.0.1",
    "port": 22555,
    "disableTransactions": true
},

"mposMode": {
    "enabled": true,
    "host": "127.0.0.1",
    "port": 3306,
    "user": "******",
    "password": "*******",
    "database": "mpos_dark",
    "checkPassword": false,
    "autoCreateWorker": false
}
```

} 

---

darkcoin.conf

rpcuser=*********
rpcpassword=****************
server=1
rpcallowip=127.0.0.1
rpcallowip=192.168.0.*

addnode=62.141.39.175
addnode=54.80.16.112
addnode=mightypool.net
addnode=213.229.88.102
addnode=85.131.127.26
addnode=q30.qhor.net
addnode=207.12.89.180
addnode=54.186.8.140
addnode=uswest01.mine.nu
addnode=uswest02.mine.nu
addnode=darkcoin.fr
addnode=asia02.mine.nu
addnode=asia01.mine.nu
addnode=42.121.58.91
addnode=drkpool.com
addnode=lotterymining.com
addnode=dark.hashrapid.com
addnode=cpu-pool.net
addnode=drk.plasr.com
addnode=Dark.SuchPool.pw
addnode=drk.yobapool.net
addnode=drk.justmine.us
addnode=nimuecrypto.com/
addnode=darckcoin.mine.nu
addnode=boundarytesters.com
addnode=cryptsy.com
addnode=mintpal.com
addnode=c-cex.com
addnode=Coin-Swap.net
addnode=coins-e.com
addnode=pool.darkcoin.io
addnode=85.102.51.213
addnode=66.128.80.203
addnode=98.178.131.72
addnode=188.142.39.105 
addnode=62.141.39.175
addnode=42.121.58.91
addnode=50.19.116.123
addnode=50.17.98.53

**Comment by gr33k** [comment]
Why suddenly closed? If you figured it out - it would be awesome if you put the fix and THEN close the bug ticket out. It just so happens I'm having the same issue.

What it may be is NOT having rpcport=<port> in your coin.conf file. 

Personally, I had found the RPC and P2P port via lsof -i (or so I thought....). This doesn't seem to be favored my NOMP...so you should explicitly set rpcport and it should work :)

**Comment by foxer666** [comment]
You can use random RPC and P2P ports in coin.conf
Example:
port=23328
rpcport=33328
