### ISSUE TITLE
npm update error

### ISSUE THREAD

**Issue by sigwo** [zone117x/node-open-mining-portal#229]
First run on Ubuntu 12.04. Node.js is up to date. I did npm cache clear ; npm update. Error below:

This is cli output:
/var/www/nomp# sudo npm update
npm http GET https://registry.npmjs.org/dateformat
npm http GET https://registry.npmjs.org/node-json-minify
npm http GET https://registry.npmjs.org/redis
npm http GET https://registry.npmjs.org/mysql
npm http GET https://registry.npmjs.org/async
npm http GET https://registry.npmjs.org/express
npm http GET https://registry.npmjs.org/body-parser
npm http GET https://registry.npmjs.org/compression
npm http GET https://registry.npmjs.org/dot
npm http GET https://registry.npmjs.org/colors
npm http GET https://registry.npmjs.org/node-watch
npm http GET https://registry.npmjs.org/request
npm http GET https://registry.npmjs.org/nonce
npm http GET https://registry.npmjs.org/bignum
npm http GET https://registry.npmjs.org/extend
npm http GET https://registry.npmjs.org/stratum-pool/0.1.6

npm ERR! Error: failed to fetch from registry: stratum-pool/0.1.6
npm ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
npm ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
npm ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
npm ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
npm ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
npm ERR!     at Request.emit (events.js:88:20)
npm ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
npm ERR!     at ClientRequest.emit (events.js:67:17)
npm ERR!     at HTTPParser.onIncoming (http.js:1261:11)
npm ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
npm ERR! You may report this log at:
npm ERR!     http://bugs.debian.org/npm
npm ERR! or use
npm ERR!     reportbug --attach /var/www/nomp/npm-debug.log npm
npm ERR!
npm ERR! System Linux 3.8.0-29-generic
npm ERR! command "node" "/usr/bin/npm" "update"
npm ERR! cwd /var/www/nomp
npm ERR! node -v v0.6.12
npm ERR! npm -v 1.1.4
npm ERR! message failed to fetch from registry: stratum-pool/0.1.6
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/nomp/npm-debug.log
npm not ok

This is from npm-debug.log:
---Snipped success above--------
verbose cache add [ 'stratum-pool@0.1.6', null ]
silly cache add: name, spec, args [ undefined,
silly cache add: name, spec, args   'stratum-pool@0.1.6',
silly cache add: name, spec, args   [ 'stratum-pool@0.1.6', null ] ]
verbose parsed url { pathname: 'stratum-pool@0.1.6',
verbose parsed url   path: 'stratum-pool@0.1.6',
verbose parsed url   href: 'stratum-pool@0.1.6' }
silly cache add: name, spec, args [ 'stratum-pool', '0.1.6', [ 'stratum-pool', '0.1.6' ] ]
verbose parsed url { pathname: '0.1.6', path: '0.1.6', href: '0.1.6' }
verbose addNamed [ 'stratum-pool', '0.1.6' ]
verbose addNamed [ '0.1.6', '0.1.6' ]
verbose raw, before any munging stratum-pool/0.1.6
verbose url resolving [ 'https://registry.npmjs.org/', './stratum-pool/0.1.6' ]
verbose url resolved https://registry.npmjs.org/stratum-pool/0.1.6
http GET https://registry.npmjs.org/stratum-pool/0.1.6
ERR! Error: failed to fetch from registry: stratum-pool/0.1.6
ERR!     at /usr/share/npm/lib/utils/npm-registry-client/get.js:139:12
ERR!     at cb (/usr/share/npm/lib/utils/npm-registry-client/request.js:31:9)
ERR!     at Request._callback (/usr/share/npm/lib/utils/npm-registry-client/request.js:136:18)
ERR!     at Request.callback (/usr/lib/nodejs/request/main.js:119:22)
ERR!     at Request.<anonymous> (/usr/lib/nodejs/request/main.js:212:58)
ERR!     at Request.emit (events.js:88:20)
ERR!     at ClientRequest.<anonymous> (/usr/lib/nodejs/request/main.js:412:12)
ERR!     at ClientRequest.emit (events.js:67:17)
ERR!     at HTTPParser.onIncoming (http.js:1261:11)
ERR!     at HTTPParser.onHeadersComplete (http.js:102:31)
ERR! You may report this log at:
ERR!     http://bugs.debian.org/npm
ERR! or use
ERR!     reportbug --attach /var/www/nomp/npm-debug.log npm
ERR!
ERR! System Linux 3.8.0-29-generic
ERR! command "node" "/usr/bin/npm" "update"
ERR! cwd /var/www/nomp
ERR! node -v v0.6.12
ERR! npm -v 1.1.4
ERR! message failed to fetch from registry: stratum-pool/0.1.6
verbose exit [ 1, true ]

**Comment by Thomasmcdaniel9** [comment]
Is there any new updates for unomp.looks like everyone has gave up on updating

**Comment by foxer666** [comment]
@Thomasmcdaniel9 
https://github.com/zone117x/node-open-mining-portal/issues/494#issuecomment-323080788
