### ISSUE TITLE
node-gyp rebuild fails during post-install npm update

### ISSUE THREAD

**Issue by JERasmussen** [zone117x/node-open-mining-portal#347]
Attempted build was on a Debian 3.2.60-1+deb7u1 PV client, running on an xcp-xapi_1.3.2-15/Debian host.  Hardware was a Gateway DX4885.  

I can send the complete log and std error/output files if you want them.

Regards,
JR
### from npm-debug.log

....
2969 verbose node_modules/stratum-pool unbuild
2970 info preuninstall stratum-pool@0.1.6
2971 info uninstall stratum-pool@0.1.6
2972 verbose true,/home/nomp/node_modules,/home/nomp/node_modules unbuild stratum-pool@0.1.6
2973 info postuninstall stratum-pool@0.1.6
2974 error multi-hashing@0.0.9 install: `node-gyp rebuild`
2974 error Exit status 1
2975 error Failed at the multi-hashing@0.0.9 install script.
2975 error This is most likely a problem with the multi-hashing package,
2975 error not with npm itself.
2975 error Tell the author that this fails on your system:
2975 error     node-gyp rebuild
2975 error You can get their info via:
2975 error     npm owner ls multi-hashing
2975 error There is likely additional logging output above.
2976 error System Linux 3.2.0-4-amd64
2977 error command "node" "/usr/bin/npm" "update"
2978 error cwd /home/nomp
2979 error node -v v0.10.26
2980 error npm -v 1.4.21
2981 error code ELIFECYCLE
2982 verbose exit [ 1, true ]
### from stderr&stdout

....
  CC(target) Release/obj.target/multihashing/nist5.o
  CC(target) Release/obj.target/multihashing/sha1.o
../sha1.c:4:25: fatal error: openssl/sha.h: No such file or directory
compilation terminated.
make: **\* [Release/obj.target/multihashing/sha1.o] Error 1
make: Leaving directory `/home/nomp/node_modules/stratum-pool/node_modules/multi
-hashing/build'
gyp ERR! build error 
gyp ERR! stack Error:`make`failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_module
s/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:
12)
gyp ERR! System Linux 3.2.0-4-amd64
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/nod
e-gyp.js" "rebuild"
gyp ERR! cwd /home/nomp/node_modules/stratum-pool/node_modules/multi-hashing
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok 
npm ERR! multi-hashing@0.0.9 install:`node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the multi-hashing@0.0.9 install script.
npm ERR! This is most likely a problem with the multi-hashing package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls multi-hashing
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "node" "/usr/bin/npm" "update"
npm ERR! cwd /home/nomp
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.21
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/nomp/npm-debug.log
npm ERR! not ok code 0

**Comment by chrisfranko** [comment]
woot woot you are the man  libssl-dev did it
