### ISSUE TITLE
Is the "p2p" option same as P2Pool?

### ISSUE THREAD

**Issue by UnsignedInt8** [zone117x/node-open-mining-portal#478]
Hello,, sir.

I'm a newer about stratum-pool, could you tell me what the "p2p" option is? What's the differences between it and P2Pool(python)?

`
    "p2p": {
        "enabled": false,

        /* Host for daemon */
        "host": "127.0.0.1",

        /* Port configured for daemon (this is the actual peer port not RPC port) */
        "port": 19333,

        /* If your coin daemon is new enough (i.e. not a shitcoin) then it will support a p2p
           feature that prevents the daemon from spamming our peer node with unnecessary
           transaction data. Assume its supported but if you have problems try disabling it. */
        "disableTransactions": true
    },
`

**Comment by zone117x** [comment]
No it's another method for getting new block update notifications from the coin daemon, should be the faster than polling and easier to setup than the blocknotify system.

**Comment by UnsignedInt8** [comment]
Thanks a lot :)
