### ISSUE TITLE
Could not parse rpc data from daemon instance

### ISSUE THREAD

**Issue by Surfang** [zone117x/node-open-mining-portal#497]
Hi!
[Pool] [sibcoin] (Thread 3) Could not parse rpc data from daemon instance  0
Request Data: {"method":"getblocktemplate","params":[{"capabilities":["coinbasetxn","workid","coinbase/append"],"rules":["segwit"]}],"id":1500812969836}
Reponse Data: Work queue depth exceeded

cat .sibcoin/sibcoin.conf
daemon=1
server=1
rpcuser=dz
rpcpassword=password
rpcport=2222

cat nomp/pool_configs/sibcoin.json
{
    "enabled": true,
    "coin": "sibcoin.json",

    "address": "SXLEQyRuH6T8zx1dnWfj6vYegJXkxGJddr",

    "rewardRecipients": {
        "SVFGK3mXmT3JdxVHodbBzR6mngBg8sFQaF": 1
    },

    "paymentProcessing": {
        "enabled": true,
        "paymentInterval": 20,
        "minimumPayment": 70,
        "daemon": {
            "host": "127.0.0.1",
            "port": 2222,
            "user": "dz",
            "password": "password"
        }
    },

    "ports": {

        "3333": {
            "diff": 0.01,
            "varDiff": {
                "minDiff": 0.01, //Minimum difficulty
                "maxDiff": 0.5, //Network difficulty will be used if it is lower than this
                "targetTime": 15, //Try to get 1 share per this many seconds
                "retargetTime": 90, //Check to see if we should retarget every this many seconds
                "variancePercent": 30 //Allow time to very this % from target without retargeting
            }
        },
        "3334": {
            "diff": 0.01
        },
        "3335": {
            "diff": 0.001
        }
    },

    "daemons": [
        {
            "host": "127.0.0.1",
            "port": 2222,
            "user": "dz",
            "password": "password"
        }
    ],

    "p2p": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 19333,
        "disableTransactions": true
    },

    "mposMode": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 3306,
        "user": "me",
        "password": "mypass",
        "database": "ltc",
        "checkPassword": true,
        "autoCreateWorker": false
    }
}

Help solve the problem plz.

**Comment by JBaczuk** [comment]
@Surfang Were you able to figure this out?

**Comment by JBaczuk** [comment]
This happened because I had the wrong ip address for the coin daemon.
