### ISSUE TITLE
XMR support?

### ISSUE THREAD

**Issue by happyxie** [zone117x/node-open-mining-portal#501]
Does this one support XMR? I have set up nomp for one coin. I want to add xmr. 

Also I saw another one node-cryptonote-pool which support XMR. Do I need to install both nomp and this one? Thanks!

**Comment by foxer666** [comment]
@happyxie 
Hi. 
XMR - CRYPTONIGHT. Stratum supports it, but need test it.
https://github.com/zone117x/node-cryptonote-pool is stand alone. Try it.

**Comment by foxer666** [comment]
After install NOMP add this code to /nomp/node_modules/stratum-pool/lib/algoProperties.js

```
cryptonight: {
        hash: function(){
            return function(){
                return multiHashing.cryptonight.apply(this, arguments);
            }
        }
    }
```

**Comment by happyxie** [comment]
Thanks for fast response. I will give it a try with the modified algoProperties.js.

**Comment by foxer666** [comment]
@happyxie 
Please, give result for us )

**Comment by happyxie** [comment]
I just tried and setup a private testnet. But I have some trouble with pool_configs. There is no conf file for the rpc info. Could you please help me with this? So I can continue the test. Thanks. Here is the monero.json file with error ([monero] (Thread 1) Could not parse rpc data from daemon instance  0
Request Data: {"method":"getinfo","params":[],"id":1504916512744}
Reponse Data:)
:  

{
    "enabled": true,
    "coin": "monero.json",

    "address": "9wviCeWe2D8XS82k2ovp5EUYLzBt9pYNW2LXUFsZiv8S3Mt21FZ5qQaAroko1enzw3eGr9qC7X1D7Geoo2RrAotYPwq9Gm8",

    "rewardRecipients": {
        "9wq792k9sxVZiLn66S3Qzv8QfmtcwkdXgM5cWGsXAPxoQeMQ79md51PLPCijvzk1iHbuHi91pws5B7iajTX9KTtJ4bh2tCh": 1.5
    },

    "paymentProcessing": {
        "enabled": false,
        "paymentInterval": 20,
        "minimumPayment": 70,
        "daemon": {
            "host": "127.0.0.1",
            "port": 28081,
            "user": "testuser",
            "password": "testpass"
        }
    },

    "ports": {
        "3008": {
            "diff": 4
        },
        "3333": {
            "diff": 32,
            "varDiff": {
                "minDiff": 2,
                "maxDiff": 512,
                "targetTime": 15,
                "retargetTime": 90,
                "variancePercent": 50
            }
        },
        "3256": {
            "diff": 256
        }
    },

    "daemons": [
        {
            "host": "127.0.0.1",
            "port": 28081,
            "user": "",
            "password": ""
        }
    ],

    "p2p": {
        "enabled": true,
        "host": "127.0.0.1",
        "port": 28080,
        "disableTransactions": true
    },

    "mposMode": {
        "enabled": true,
        "host": "127.0.0.1",
        "port": 3306,
        "user": "root",
       "password": "",
        "database": "MPOSmagi",
        "checkPassword": true,
        "autoCreateWorker": false
    }

}

**Comment by foxer666** [comment]
@happyxie 
Is it real wallets?
9wviCeWe2D8XS82k2ovp5EUYLzBt9pYNW2LXUFsZiv8S3Mt21FZ5qQaAroko1enzw3eGr9qC7X1D7Geoo2RrAotYPwq9Gm8
9wq792k9sxVZiLn66S3Qzv8QfmtcwkdXgM5cWGsXAPxoQeMQ79md51PLPCijvzk1iHbuHi91pws5B7iajTX9KTtJ4bh2tCh
Why so long? May be error?

For work you need synsronised wallet and more than 0 peers connected.
Request Data: {"method":"getinfo","params":[],"id":1504916512744}
Reponse Data:)
:

NOMP can't receive and parce answer from wallet via RPC.
Try getinfo in wallet dirrectly.

**Comment by happyxie** [comment]
Those are testnet wallets. I am not familiar with xmr. Will take some time to check it. Right now, I will go for simple plan first, install separate package for each coin. If I figure out how to set up xmr with nomp, I will report it. Thanks for your help.

**Comment by shtse8** [comment]
Thanks for your information. I am trying.

**Comment by jabiers** [comment]
I am trying to make monero pool.
monero has rpc methods difference with bitcoin's rpc methods.

it makes error.

simply getinfo method doesn't exist on monero.
it should get_info.

**Comment by foxer666** [comment]
@jabiers 
Hi
Recompile wallet and change command
https://github.com/monero-project/monero/blob/591e53445b2643af1e9a5266ffa5324cad758255/src/rpc/daemon_messages.cpp

**Comment by jabiers** [comment]
@foxer666 
have you ever succeed in making?

**Comment by foxer666** [comment]
@jabiers 
Hi. I must try?

**Comment by ar1k88** [comment]
Any news on this?..

**Comment by foxer666** [comment]
Hi guys. Now work on more easy problems. XMR - global problem. Can't help now, try this week.

**Comment by zone117x** [comment]
Nomp only works on cryptocurrencies based on bitcoin. Monero is based on Bytecoin/cryptonote which is why a separate pool implementation was created for it: https://github.com/zone117x/node-cryptonote-pool

**Comment by MyS5Droid** [comment]
Reopen please, https://github.com/zone117x/node-cryptonote-pool does not support stratum to stratum.

Please add it in, it is a planned feature...

**Comment by Admiral-Noisy-Bottom** [comment]
Cryptonight does work in Node-Cryptonote-Pool. I've got it working for Monero (XMR). Well, I think it's working, I've got no miners so I don't know if it will pay them when a block is found. You can check it out at [(http://xmr.pictureslots.net.au)]

I'm still working on it so it goes up and down, but it does work with a bit of fiddling around.
