### ISSUE TITLE
Can I load balance between two bitcoind instaces by switching share submission

### ISSUE THREAD

**Issue by zefirka** [zone117x/node-open-mining-portal#505]
Hello! Sorry for maybe stupid question.

Let's suppose that I run two instances of `bitcoind` on my server. Can I accept `block template` from **first** instance but submit share to **second**? If I understand it correct: `getblocktemplate` is stateless in terms of blockchain, and pool sever can choose which transactions to include in candidate block. And blocks that hashing by miners can be submitted to ant `bitcoind` instance. 

I have a trouble with bitcoin daemon. It's really overloaded by RPC calls and I want to load balance between two instances and now I'm finding way how to do it. 

Thank you

**Comment by foxer666** [comment]
@zefirka 
Hi. I think it will not work.

You can off rpc calls to wallet.
Add in coin config:
blocknotify=node /pool/scripts/cli.js blocknotify coinname %s

And in pool config add
"blockRefreshInterval": 0

Totaly wallet will notify pool about blocks.

**Comment by zefirka** [comment]
@foxer666 Thank you. I tried that and it was really unloaded bitcoind. 

But can someone explain to me why my scheme with load balance between instances will not work?

**Comment by foxer666** [comment]
@zefirka 
It will work if change blocknotify script code for two deamons.
