### ISSUE TITLE
RPC does not connect with litecoin

### ISSUE THREAD

**Issue by djleoli** [zone117x/node-open-mining-portal#530]
it seems that according to reading in github in other projects the RPC commands changed with an update, and now NOMP can not connect. I leave my configuration
litecoin.conf

daemon=1
rpcuser=litecoinrpc
rpcpassword=xxxx
rpcport=19332

litecoin.json

{
    "enabled": true,
    "coin": "litecoin.json",

    "address": "xxxx",

    "rewardRecipients": {
        "xxxx": 1.0,
        "xxxxx": 0.5
    },

    "paymentProcessing": {
        "enabled": true,
        "paymentInterval": 20,
        "minimumPayment": 70,
        "daemon": {
            "host": "127.0.0.1",
            "port": 19332,
            "user": "litecoinrpc",
            "password": "xxxx"
        }
    },

and if I throw listening command the litecoin ports are listening

tcp        0      0 127.0.0.1:19332         0.0.0.0:*               ESCUCHAR    29406/litecoind 
tcp        0      0 127.0.0.1:52615         127.0.0.1:19332         TIME_WAIT   -               
tcp        0      0 127.0.0.1:52666         127.0.0.1:19332         TIME_WAIT   -               
tcp        0      0 127.0.0.1:52716         127.0.0.1:19332         TIME_WAIT   -               

 
but when starting nomp, only connects me ok earthcoin, but litecoin not indicating rejected connection. Also two more coins give me the same error, worldcoin and auroracoin

2017-12-19 13:02:09 [Switching] [Setup] (Thread 1) Loading last proxy state from redis
2017-12-19 13:02:09 [Pool]      [litecoin] (Thread 1) Could not start pool, error with init batch RPC call: {"type":"offline","message":"connect ECONNREFUSED"}
2017-12-19 13:02:10 [Website]   [Server] Website started on 192.168.120.243:80
2017-12-19 13:02:10 [Switching] [Setup] (Thread 2) Loading last proxy state from redis
2017-12-19 13:02:10 [Pool]      [litecoin] (Thread 2) Could not start pool, error with init batch RPC call: {"type":"offline","message":"connect ECONNREFUSED"}

some idea of how to solve the problem

**Comment by 200MPH** [comment]
Have you try set up daemons?

```
"daemons": [
        {   //Main daemon instance
            "host": "127.0.0.1",
            "port": 19332,
            "user": "testuser",
            "password": "testpass"
        }
    ],
```

**Comment by djleoli** [comment]
Yes, it's all right. because I did everything the same in all currencies, using the configuration instructions, and a few months ago litecoin worked very well, turn off the server, yesterday I clicked it again and leaving the exact configuration does not connect, instead earthcoin worked before and now continues to connect without problems, I repeat lei in another project (z-nomp) that litecoin from an update change the rpc commands...

**Comment by foxer666** [comment]
server=1

**Comment by djleoli** [comment]
no is not funcion

**Comment by djleoli** [comment]
well after I found I found that my configuration was missing from my part and so that did not connect, I close the issue, it was just filling the daemon information correctly
