### ISSUE TITLE
NOMP won't start when running node directly from binary

### ISSUE THREAD

**Issue by Dizeeee** [zone117x/node-open-mining-portal#557]
I'm trying to run NOMP as a systemd service, and for whatever reason I cannot run it when running `/usr/bin/nodejs /path/to/nomp/init.js`. Node will throw this error:

```
module.js:672
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: Module did not self-register.
    at Object.Module._extensions..node (module.js:672:18)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/root/pool/nomp/node_modules/bignum/index.js:4:11)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
```

However, when I run `node init.js` while in NOMP's directory it works perfectly normally. I'm running Ubuntu 16.04 on a DigitalOcean droplet with node version 0.10.25. Is there any way I can fix this within systemd or write a simple script to start the service?

**Comment by zone117x** [comment]
The working directory probably needs to be set to /path/to/nomp first. For example try changing your service start script to something like:
```
cd /path/to/nomp
/usr/bin/nodejs init.js
```

**Comment by Dizeeee** [comment]
How would I go about doing this in a way that systemd will run it? Systemd requires absolute paths which forces me to use /usr/bin/nodejs in the first place

**Comment by zone117x** [comment]
Could create another script with snippet above, then call that script from systemd

**Comment by Dizeeee** [comment]
I have a script written that is nearly identical to this. The problem seems to be caused by running `/usr/bin/nodejs` instead of `node`.

**Comment by Dizeeee** [comment]
To be more specific, I think NVM might not be applying the right version to the binary

**Comment by dmalf** [comment]
In that case, get the absolute path to whatever version of node you are using. So “nvm use [version goes here]”, then run “which node” to tell you the absolute path for that specific version that nvm installs and sets up behind the scenes for you.
