### ISSUE TITLE
ERR! Failed at the multi-hashing@0.0.9 install script.

### ISSUE THREAD

**Issue by paketeh** [zone117x/node-open-mining-portal#558]
Hi

Any help with this issue would be more than welcome:

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:2
3)
gyp ERR! stack     at ChildProcess.emit (events.js:160:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.13.0-1008-gcp
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "reb
uild"
gyp ERR! cwd /opt/nomp/node_modules/multi-hashing
gyp ERR! node -v v9.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! multi-hashing@0.0.9 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the multi-hashing@0.0.9 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-02-01T14_59_25_605Z-debug.log

---

nodejs version is 9.4.0
npm version is 5.60
Running this as root.

Also tried with npx, same problem :/

Thanks in advance!!

- paketeh

**Comment by foxer666** [comment]
Did You read Requirements?
https://github.com/zone117x/node-open-mining-portal#requirements
Nomp works with 0.10.x

**Comment by paketeh** [comment]
Totally true! Solved, many thanks!
