### ISSUE TITLE
Support for coins without getblockchaininfo method

### ISSUE THREAD

**Issue by ImrieA** [zone117x/node-open-mining-portal#588]
Hello,

Any tips on where to start modifying NOMP to support coins which don't have a getblockchaininfo() method ? Currently met with the below error when starting the pool
 
 `[Pool]      [BosonCoin] (Thread 2) Could not start pool, error with init RPC getblockchaininfo - {"code":-32601,"message":"Method not found"}`

Thanks

**Comment by reappergrimd** [comment]
There was a change in https://github.com/zone117x/node-stratum-pool/tree/master/lib 3 days ago , i went into the lib structure to revert the changes made myself for my pool for the older coins

**Comment by TheCryptoServices** [comment]
Ah! I'm having that same issue...
Can you explain how to fix it please?

Thanks

**Comment by HashUnlimited** [comment]
backporting support was added by #ahmedbody in the correct repo node-stratum-pool

**Comment by red0bear** [comment]
how much time to that be done ? Peercoin is falling ....

**Comment by 1307cd** [comment]
Hi guys, from my understanding it is allready done, but I also have two coins, which are not working. Magnet and Pepecoin...

**Comment by 1307cd** [comment]
Sorry my bad...
