### ISSUE TITLE
Luck / Too many shares to find a block, / Bad Stats

### ISSUE THREAD

**Issue by tperalta82** [zone117x/node-open-mining-portal#591]
Hey Everyone, 
I run some considerably big pools on multiple algorithms, and for the last 2 months i'd say, out of nowhere the luck stats are going bad and bad almost everyday, i tried everything from checking difficulty settings with/without vardiff, checking logs for errors  (no errors) etc.

Everything was opkay until like 2 months ago.

https://polis.multipools.club/index.php?page=statistics&action=blocks

Any ideas?

I have a somewhat good setup all with SSD's lots of ram, different stratum/frontend and database servers

**Comment by tperalta82** [comment]
Fixed on my end

**Comment by youngwebs** [comment]
@tperalta82 I have a similar (the same?!) issues since 2-3 months. Can you share what you did here?
