### ISSUE TITLE
Mining on Segwit address not working. 

### ISSUE THREAD

**Issue by cornac** [zone117x/node-open-mining-portal#614]
I try mining to segwit address. Add it to coin config. 

 "address": "SPK6qTfFvotsL4aLn6diezGDezvoNGH6q8",
But it mined to legacy address. And this address is not in wallet. https://chainz.cryptoid.info/dgb/address.dws?D7ACLspkVrbxLkyUyFeCerHFtMRfrumkrh.htm

How can I tak back  my reward? And how to setup for mine to segwit address?

**Comment by HashUnlimited** [comment]
#604 
#609

**Comment by cornac** [comment]
I see this. But where I can see example of this parameters?

**Comment by HashUnlimited** [comment]
#603

**Comment by HashUnlimited** [comment]
https://github.com/zone117x/node-open-mining-portal/blob/dev/coins/chaincoin.json
