### ISSUE TITLE
NOMP Getting error when trying to connect to certain wallets

### ISSUE THREAD

**Issue by phoeniixdotcom** [zone117x/node-open-mining-portal#638]
I'm getting an error trying to connect to certain scrypt wallets (Aricoin, Auroracoin, Cash).  Other scrypt wallets are fine (Digibyte, Monacoin, Bata).  I have confirmed that rpc port is open and accessible, but rpc call returns empty string.  Any ideas what I might be doing wrong?

> 2018-10-24 08:59:10 [Pool]	[auroracoin] (Thread 1) Could not parse rpc data from daemon instance  0
Request Data: {"method":"getpeerinfo","params":[],"id":15403967509xx}
Reponse Data:

**Comment by phoeniixdotcom** [comment]
Hey thanks for responding.

My conf files pretty much all look like this for wallets that work and wallets that don't:
`server=1
showmetrics=1

rpcuser=xxxxuser
rpcpassword=xxxxpass
rpcallowip=10.x.x.0/24
rpcbind=0.0.0.0`

I enable server and bind to all ip's and allow my private subnet.  The port is confirmed live with nmap.  However it seems like some of these cheap coins don't provide a cli that I can access with so I don't actually know if the rpcport is valid.  Was hoping others might have seen this problem, but I'm seeing the same response "" empty string for the bad wallets.  It could just be poorly written wallets that don't implement getpeerinfo I guess.  I'm also only trying scrypt wallets, no other algorithm.

**Comment by paintballrefjosh** [comment]
Use postman or something similar to test RPC connectivity from a remote host.  Then run some basic commands to see if all is working properly.  GetInfo GetMiningInfo, GetPeerInfo etc

**Comment by phoeniixdotcom** [comment]
Ok, I just discovered that the daemon file for these scrypt coins contains the cli commands for accessing rpc commands, ie for 42 coin I get the error above when NOMP starts up, but when i run `./42d getpeerinfo` it successfully returns json for all the peers for the 42 wallet.  Still digging around for more examples.

**Comment by paintballrefjosh** [comment]
If it doesn't have a XX-cli binary you can try something like this.  Verge is the same way:

`/opt/mining/nodes/xvg/VERGEd -rpcpassword=somepass -rpcuser=someuser -rpcconnect=10.1.2.3 -rpcport=8348 getmininginfo`

**Comment by phoeniixdotcom** [comment]
Thanks again, so I can call getinfo from 42d on the wallet server, but get 403 when calling from my nomp server, the 403 response is 0 bytes, which is what nomp is seeing.  I must have a config problem with the wallet not allowing external requests.  I thought the settings above open that up, but I'll have to play with it some more.  Thx for help and ideas.

**Comment by paintballrefjosh** [comment]
Ok looking at the sample config for 42 coin they implement the `rpcallowip` different than most.  I'm running a wallet that does hit also but I don't remember which one.  Try this instead:

`rpcallowip=10.X.X.*`

For reference: https://github.com/42-coin/42/blob/master/contrib/debian/examples/42.conf

**Comment by phoeniixdotcom** [comment]
Yes, that was it... now NOMP is trying to call `getblockchaininfo`, but that rpc method isn't found for 42 with `./42d help`.  At least that is probably my problem with the other coins.  I'll see if they work now.

**Comment by phoeniixdotcom** [comment]
And finally, after debugging code, I discovered that with commit #4f298c I just need to add hasGetInfo to my coin config

`
{
    "name": "42",
    "symbol": "42",
    "algorithm": "scrypt",
    "hasGetInfo": true
}
`

problem solved, thx for help!
