### ISSUE TITLE
Can't start node init.js

### ISSUE THREAD

**Issue by webdev866** [zone117x/node-open-mining-portal#707]
I have the following issue when I do : node init.js OR sudo node init.js

root@4321-51a430:~/nomp# sudo node init.js
undefined:1
{"enabled":true,"coin":"dollar.json","address":"7kA7WpQFHutJA5aTrfqZ67nFMLTDMC4emX","rewardRecipients":{75ZNRZpEqYBM72GwGi6LCjaKM5Ao715ijD},"paymentProcessing":{"enabled":true,"paymentInterval":20,"minimumPayment":70,"daemon":{"host":"127.0.0.1","port":17703,"user":"rpc_dollar","password":"123456"}},"ports":{"3008":{"diff":8},"3032":{"diff":32,"varDiff":{"minDiff":8,"maxDiff":512,"targetTime":15,"retargetTime":90,"variancePercent":30}},"3256":{"diff":256}},"daemons":[{"host":"127.0.0.1","port":17703,"user":"rpc_dollar","password":"123456"}],"p2p":{"enabled":false,"host":"127.0.0.1","port":19333,"disableTransactions":true},"mposMode":{"enabled":false,"host":"127.0.0.1","port":3306,"user":"me","password":"mypass","database":"ltc","checkPassword":true,"autoCreateWorker":false}}
                                                                                                        ^

SyntaxError: Unexpected number in JSON at position 104
    at JSON.parse (<anonymous>)
    at /root/nomp/init.js:102:32
    at Array.forEach (<anonymous>)
    at buildPoolConfigs (/root/nomp/init.js:100:31)
    at init (/root/nomp/init.js:431:19)
    at Object.<anonymous> (/root/nomp/init.js:443:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
root@4321-51a430:~/nomp#

**Comment by dylansproule** [comment]
Clear, rewardRecipients isn’t an object of strings

**Comment by webdev866** [comment]
@dylansproule  thank you for your response, can you please tell me how to resolve it? The funny thing is that it was working fine with all that configuration, when I rebooted my server i couldn't get it to work.

**Comment by dylansproule** [comment]
Can you try a toString() on the value?

**Comment by webdev866** [comment]
@dylansproule I'm still facing the same issue, here is my config:

{
    "enabled": true,
    "coin": "dollar.json",

    "address": "7kA7WpQFHutJA5aTrfqZ67nFMLTDMC4emX",

    "rewardRecipients": {
    "75ZNRZpEqYBM72GwGi6LCjaKM5Ao715ijD"
},

    "paymentProcessing": {
        "enabled": true,
        "paymentInterval": 20,
        "minimumPayment": 70,
        "daemon": {
            "host": "127.0.0.1",
            "port": 17703,
            "user": "rpc_dollar",
            "password": "123456"
        }
    },

    "ports": {
        "3008": {
            "diff": 8
        },
        "3032": {
            "diff": 32,
            "varDiff": {
                "minDiff": 8,
                "maxDiff": 512,
                "targetTime": 15,
                "retargetTime": 90,
                "variancePercent": 30
            }
        },
        "3256": {
            "diff": 256
        }
    },

Error:

SyntaxError: Unexpected token } in JSON at position 140
    at JSON.parse (<anonymous>)
    at /root/nomp/init.js:102:32
    at Array.forEach (<anonymous>)
    at buildPoolConfigs (/root/nomp/init.js:100:31)
    at init (/root/nomp/init.js:431:19)
    at Object.<anonymous> (/root/nomp/init.js:443:3)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)

**Comment by webdev866** [comment]
I figured it out.

the solution should be 

"rewardRecipients": {
"75ZNRZpEqYBM72GwGi6LCjaKM5Ao715ijD":100
},
