### ISSUE TITLE
quark based coin always rejects shares

### ISSUE THREAD

**Issue by dworld01** [zone117x/node-open-mining-portal#730]
I have installed for quark also coin based mining pool
website - http://pool.mining.edenchain.finance

but while trying to mine each and every time shares getting rejected - "reason low difficulty level" 
pls let me know the issue or how to resolve

**Comment by clustercrypto** [comment]
please check your port rpc pool and check firewall allow port pool on server !

**Comment by dworld01** [comment]
thanks for response
