### ISSUE TITLE
Error: Unauthorized

### ISSUE THREAD

**Issue by Thetima4** [zone117x/node-open-mining-portal#735]
Hello!  I just installed nomp.  When I connect the miner, the pool log  shows an error: Unauthorized <wallet_address> [::ffff:ip_address].  Then the miner shuts down.  How to solve this problem?

Привет! Я только что  установил nomp. У меня во время подключения майнера в логе пула показывается ошибка: Unauthorized <wallet_address> [::ffff:ip_address]. Дальше майнер отключается. Как решить эту проблему?

**Comment by Thetima4** [comment]
I was able to solve this problem!  it was necessary to remove the worker names.

**Comment by ghost** [comment]
> I was able to solve this problem!  it was necessary to remove the worker names.

I have the same issue. Where did you remove the worker names from?

**Comment by Thetima4** [comment]
> > I was able to solve this problem!  it was necessary to remove the worker names.
> 
> I have the same issue. Where did you remove the worker names from?

I removed the worker name in the miner settings and used only the wallet address. I had the password as the worker name.
